### ISSUE TITLE
When loading spreadsheets with column_type text cell numeric values get altered 

### ISSUE THREAD

**Issue by hendrikmh** [wireservice/agate-excel#21]
I am trying to load tables from spreadsheets that contain text and numeric information (i.e. serial_numbers like "1234567890" and "12GNHGZ34567655". I have set column_types to be text only (confirmed to work) - however in the target table numeric values have been treated as float resulting in "1234567890.0". Alphanumeric values just stay as is.

**Comment by hendrikmh** [comment]
if I load with pyexcel and create the agate table from object is works as expect:

```
import agate
import agatesql
import agateexcel
from pyexcel_xls import get_data
tester = agate.TypeTester(types=[agate.Text()])
data = get_data(filename)
table = agate.Table.from_object(data['0'],column_types=tester)
print(table.print_json())
```

going direct from Excel with this code creates the unwanted alterations:

```
import agate
import agatesql
import agateexcel
```

initializing filename, sheet etc....

```
tester = agate.TypeTester(types=[agate.Text()])
table = agate.Table.from_xls(filename, sheet=sheet,column_types=tester)
print(table.print_json())
```

**Comment by jpmckinney** [comment]
Can you provide a sample file and complete sample code (setting filename, sheet, etc.)? I can't reproduce the issue.
