### ISSUE TITLE
openpyxl's read_only mode breaks parsing on certain sheets

### ISSUE THREAD

**Issue by rdmurphy** [wireservice/agate-excel#22]
`openpyxl`'s `read_only` option for `load_workbook` can cause issues with parsing spreadsheets that do not properly report their dimensions. [This issue is documented in the `openpyxl`'s documentation](https://openpyxl.readthedocs.io/en/default/optimized.html#worksheet-dimensions).

([Here is a direct link to the spreadsheet surfacing this issue](https://www.ethics.state.tx.us/tedd/CTA_Office_Sought.nopag.xlsx).)

While `openpyxl` does give you a possible solution for resetting the dimensions — `ws.max_row = ws.max_column = None` — it may be easier to add an option for disabling `read_only` mode. I'm not sure if that dimension resetting is viable across all the possible sheets you may hit. (I did confirm, however, that it solved this particular spreadsheet's issue.)

This issue also manifests in csvkit too, and prevents `in2csv` from being able to parse this sheet.

**Comment by jpmckinney** [comment]
I'd accept a pull request to add an option to disable `read_only` mode (which is used by default for better performance).
