### ISSUE TITLE
Breaking change in openpyxl 2.6.0

### ISSUE THREAD

**Issue by wagonli** [wireservice/agate-excel#26]
openpyxl 2.6.0 has a breaking change producing the following error :
`iter_rows() got an unexpected keyword argument 'row_offset'`

The `row_offset` parameter does not exist anymore and is replaced by a combination of `min_col` `max_col`

forcing install of openpyxl 2.3.0 works around the issue.

You should freeze the dependencies version to avoid that kind of issues.

**Comment by wagonli** [comment]
@timfreund @onyxfish Is there any good reason not to freeze the requirements to a specific version (instead of at least a version) ?
This would avoid other kind of breaking changes in the future

**Comment by timfreund** [comment]
I tend to go with this or something like this on my projects:  https://www.kennethreitz.org/essays/a-better-pip-workflow

In short, I let the development version float with an unversioned requirements file so I stay up to date with upstream releases, and then I freeze my dependencies to get an exact versioned list when creating a release.  Package developers stay up to date, and package users get a known good requirements list.

In this case, openpyxl 2.3.0 was released in 2015.  If someone is using agate-excel in conjunction with other code that make use of openpyxl, it's likely that the other code will be using a later version.

That all said, I'm open to suggestions and directions from the agate-excel project team.  These are my first two PRs to the project, so I wanted to keep them as small and focused as possible.

**Comment by leftiness** [comment]
They seem [unrepentant]. I didn't see an indication of the deprecation they mentioned.

[unrepentant]: https://bitbucket.org/openpyxl/openpyxl/issues/1177/typeerror-iter_rows-got-an-unexpected

**Comment by jpmckinney** [comment]
Fixed by #27 - thanks!
