### ISSUE TITLE
File isnt closed when we read a wrong sheet

### ISSUE THREAD

**Issue by hoangddt** [wireservice/agate-excel#34]
My intention is to loop and read data from all sheet:

``` python
sheet = 0
while True:
    # try to parse at all sheet
    try:
        table = agate.Table.from_xlsx(filename, sheet=sheet)
    except IndexError:
        break
    sheet = sheet + 1
```

The problem is: if I pass the sheet argument which does not exist, then it throws an exception and it doesn't close the file. I received this warning:

``` sh
sys:1: ResourceWarning: unclosed file <_io.BufferedReader name='filename.xlsx'>
```

**Comment by jpmckinney** [comment]
Now fixed in HEAD, thanks for reporting!
