### ISSUE TITLE
Dependency openpyxl dropped support for python<3.6

### ISSUE THREAD

**Issue by leftiness** [wireservice/agate-excel#35]
agate-excel==0.2.3 depends on openpyxl>=2.3.0. openpyxl released 3.0.0 on 2019-09-25, which breaks compatibility with python<3.6. Should agate-excel depend on openpyxl>=2.3.0,<3?

links

* https://github.com/wireservice/agate-excel/blob/b87f4563d1f337b24156228ac62ddabd3abcc16a/requirements-py3.txt
* https://bitbucket.org/openpyxl/openpyxl/commits/5eaaf27880d0
* https://bitbucket.org/openpyxl/openpyxl/commits/2b0f42fd2a501905b40c0b434cbc6f16ff51fffe

**Comment by jpmckinney** [comment]
On one hand, [2.7 and 3.5 are not yet end-of-life](https://devguide.python.org/devcycle/#end-of-life-branches), so we don't want to require >=3.6 like openpyxl. On the other hand, if a user wants to use Python>=3.6 and take advantage of openpyxl>=3, then they should be free to. The one downside to keeping the requirements as-is is that Python<3.6 users will need to set openpyxl<3 when installing agate-excel (whether in a pip command or requirements file). That downside doesn't seem important enough to constrain user freedom in their choice of openpyxl version.

**Comment by jpmckinney** [comment]
2.7 is EOL 2019-01-01 and 3.5 is EOL 2020-09-13, so we can remove them both by next September, at which point this issue can be closed. https://devguide.python.org/#branchstatus
