### ISSUE TITLE
Test failure with openpyxl 3.0.7

### ISSUE THREAD

**Issue by rmcgibbo** [wireservice/agate-excel#45]
Hi,

I see a single test failure related to ambiguous dates in the NixOS builds of this package: https://nix-cache.s3.amazonaws.com/log/gj2vn41aa7ccl3frmkcvssn4na8z3ngm-python3.8-agate-excel-0.2.3.drv
I was able to git bisect the change to our upgrade of the openpyxl dependency from 3.0.6 to 3.0.7 -- the test succeeds with 3.0.6 and fails with 3.0.7. I haven't investigated further, but I wanted to let you know, in case you have any suggestions on how to fix this.

**Comment by rmcgibbo** [comment]
Looking at their release notes, it's probably related to https://foss.heptapod.net/openpyxl/openpyxl/-/merge_requests/395/

**Comment by jpmckinney** [comment]
Thank you for reporting the issue!
