### ISSUE TITLE
Version constraint on openpyxl

### ISSUE THREAD

**Issue by havardAasen** [wireservice/agate-excel#47]
After the fix for #45 the test fails with older versions of openpyxl. Should the version constraint in `setup.py` be updated to reflect this? As this package stands now, it should be constrained to `>= 3.0.7`

I haven't looking into the possibility to rewrite the test and take openpyxl version into consideration.

**Comment by jpmckinney** [comment]
I wouldn't say the package is constrained to `>= 3.0.7` – it's only one expectation in the tests that change depending on the version. We *could* constrain it in the `test` under `extras_require`, but who is running these tests on old versions of openpyxl?

**Comment by havardAasen** [comment]
I did, that's why i created this issue.

**Comment by jpmckinney** [comment]
Okay - but you know the answer is just to upgrade openpyxl. What's the problem? Why do you need to run the tests on an old version?

**Comment by jpmckinney** [comment]
Closing as no response.
