### ISSUE TITLE
Designate header row when using `from_xls` or `from_xlsx`

### ISSUE THREAD

**Issue by rdmurphy** [wireservice/agate-excel#7]
In our `tx_salaries` repo, we use `csvkit` (and by extension, now `agate-excel`!) to prep Excel files for processing. An extra option we also have — after the conversion has happened — is to [peel off rows until we hit the header row](https://github.com/texastribune/tx_salaries/blob/master/tx_salaries/utils/transformer.py#L34-L35). We always know where that header row is, so we can pass that index in and be good to go.

When I was doing some tests with `agate-excel` directly, I quickly hit that wall. It gets a little funky if an Excel spreadsheet has some useless extra rows before the data.

That sound like something that'd be worth having as part of the package? I imagine it could be another option to be passed into the `from_` commands.

``` python
table = agate.Table.from_xlsx('i_dont_want_your_extra_rows.xlsx', header_row=4)
```

The biggest decision to make? Do you use zero-based indexing, or start at 1 like Excel? :grimacing: (We forget what we picked **constantly**.)

**Comment by jpmckinney** [comment]
Related https://github.com/wireservice/csvkit/issues/669

**Comment by jpmckinney** [comment]
Also https://github.com/wireservice/csvkit/issues/336
